.PHONY: clean All

All:
	@echo "----------Building project:[ flip_flop_irq_vectored - Debug ]----------"
	@cd "flip_flop_irq_vectored" && "$(MAKE)" -f  "flip_flop_irq_vectored.mk" && "$(MAKE)" -f  "flip_flop_irq_vectored.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ flip_flop_irq_vectored - Debug ]----------"
	@cd "flip_flop_irq_vectored" && "$(MAKE)" -f  "flip_flop_irq_vectored.mk" clean
